### PR TITLE
remove snafu

### PR DESCRIPTION
**Pull request by burrbull**

### CODE REVIEW

**Comment by XAMPPRocky** [comment]
Thank you for your PR, and congrats on your first contribution! 🎉

**Comment by torokati44** [comment]
BTW This PR bumped the `flume` dependency to `0.11.0` in the main crate, but not in `macros`, thereby causing a version duplication of it:
https://github.com/ruffle-rs/ruffle/actions/runs/8701668584/job/23864127408#step:5:589

You could consider setting up the common dependencies as workspace level ones, a la: https://github.com/ruffle-rs/ruffle/pull/15868

**Comment by XAMPPRocky** [comment]
Yes we should, PR doing so are welcome this crate was made before that feature existed.

**Comment by torokati44** [comment]
There you go: https://github.com/XAMPPRocky/fluent-templates/pull/64

**Pull request merged**
