### PR TITLE
chore: Bump `fluent-langneg` to `v0.14` and `heck` to `v0.5.0`

### PR DESCRIPTION
**Pull request by torokati44**
Depends on https://github.com/XAMPPRocky/fluent-templates/pull/64.

### CODE REVIEW

**Comment by torokati44** [comment]
This is not going to be trivial:

https://github.com/projectfluent/fluent-langneg-rs/blob/main/CHANGELOG.md#fluent-langneg-0140-december-13-2023

>    Move from using unic-langid to icu-locid.
>    Re-export LanguageIdentifier.

**Comment by torokati44** [comment]
Especially since `fluent-bundle` still depends on `unic-langid` unconditionally:
https://github.com/projectfluent/fluent-rs/blob/18343761a6048f0dd8304dc2753607c303b88c43/fluent-bundle/Cargo.toml#L42

This can wait...

**Comment by alerque** [comment]
The `fluent-langneg` crate should *not* be bumped to something newer that `fluent` and other crates in that workspace depend on (currently v0.13). The reason it is held back is there langneg crate moved onto some ICU types that conflict with the old ones. There is work in progress to get `fluent` updated to match so they can both move on together, but it is not released yet.

I don't know about `heck`, but `fluent-langneg` should not be bumped here yet. Even if you hack your way through the type mismatch it will create even more problems for downstream consumers that also use Fluent.

**Comment by torokati44** [comment]
Yes, I reached the same conclusion myself. :)
If/when the `heck` update becomes important, I can open another PR for that. 
Until then, feel free to close this one.

**Pull request closed without merging**
